import sql from 'mssql';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../../.env.development') });

/**
 * Seed departments from SPO_Dev data
 *
 * Server 76 (10.73.148.76) - ALL DATABASES
 * - kpi-db: Main KPI application database (where departments are stored)
 * - SPO_Dev: Source of department names
 * - CAS_Dev: Employee data
 *
 * Run: npx tsx server/scripts/seed-spo-departments.ts
 */

const config = {
  server: process.env.KPI_DB_HOST || '10.73.148.76',
  database: process.env.KPI_DB_NAME || 'kpi-db',
  user: process.env.KPI_DB_USER || 'inn@admin',
  password: process.env.KPI_DB_PASSWORD || 'i@NN636195',
  port: parseInt(process.env.KPI_DB_PORT || '1433'),
  options: {
    trustServerCertificate: true,
    encrypt: false,
  },
};

// All departments from SPO_Dev (SDM and SKD)
const SDM_DEPARTMENTS = [
  { dept_code: 'SDM', dept_id: '636050', name_en: 'PRESIDENT OF SDM', type: 'JP', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '626070',
    name_en: 'EVP OF MANUFACTURING (SAITOH SAN)',
    type: 'JP',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626001',
    name_en: 'VP OF QA (NISHIJIMA SAN)',
    type: 'JP',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626200',
    name_en: 'VP OF MANUFACTURING (HATA SAN)',
    type: 'JP',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636100',
    name_en: 'VP OF ADMINISTRATION (OI SAN)',
    type: 'JP',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616002',
    name_en: 'UTILITIES (DIRECT) (84%)',
    type: 'Utilities',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '626017',
    name_en: 'UTILITIES (INDIRECT) (13%)',
    type: 'Utilities',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636018',
    name_en: 'UTILITIES (SGA) (3%)',
    type: 'Utilities',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636004',
    name_en: 'MANAGEMENT FEE (SGA)',
    type: 'JP',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636060',
    name_en: 'MANAGEMENT FEE (SGA) (SHIBAYAMA)',
    type: 'JP',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626005',
    name_en: 'MANAGEMENT FEE (INDIRECT)',
    type: 'JP',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '636006', name_en: 'SS FEE', type: 'SSFEE', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '636007',
    name_en: 'COMMISSION DIAT',
    type: 'SSFEE',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636008',
    name_en: 'COMMISSION DIAS',
    type: 'SSFEE',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636009',
    name_en: 'TECHNICAL CENTER - DIESEL',
    type: 'SSFEE',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636014',
    name_en: 'TECHNICAL CENTER - GDP',
    type: 'SSFEE',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '636011', name_en: 'LABOUR UNION', type: 'Union', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '636012',
    name_en: 'ALLOWANCE FOR JAPANESE',
    type: 'JP',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626024',
    name_en: 'SUPPORT GDP PROBLEM-HONDA SORTING',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626042',
    name_en: 'SUPPORT QUALITY PROBLEM OF HP5',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626043',
    name_en: 'SUPPORT QUALITY PROBLEM OF HP5S (HOUSING LEAK)',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626044',
    name_en: 'SUPPORT QUALITY PROBLEM OF RC4 (PRV)',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626045',
    name_en: 'SUPPORT QUALITY PROBLEM FOR CUMMIN MODEL',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626046',
    name_en: 'SUPPORT TOYOTA GD',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626047',
    name_en: 'SUPPORT QUALITY PROBLEM OF HP5E (PUMP LOCK)',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626048',
    name_en: 'SUPPORT QUALITY PROBLEM OF HP5S (PCV O-RING TEAR)',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626049',
    name_en: 'SUPPORT QUALITY PROBLEM OF HP5S (CYLINDER SEAT BALL VALVE DENT)',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616091',
    name_en: 'SUPPORT QUALITY ISSUE : HP3',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616092',
    name_en: 'SUPPORT QUALITY ISSUE : HP5',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616093',
    name_en: 'SUPPORT QUALITY ISSUE : HP5-E',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616094',
    name_en: 'SUPPORT QUALITY ISSUE : RC',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616095',
    name_en: 'SUPPORT QUALITY ISSUE : G2&G3',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616096',
    name_en: 'SUPPORT QUALITY ISSUE : G4',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616097',
    name_en: 'SUPPORT QUALITY ISSUE : UC',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616098',
    name_en: 'SUPPORT QUALITY ISSUE : GDP',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626078',
    name_en: 'SKD PLANT EXPANSION',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636101',
    name_en: 'DIRECTOR OF ADMINISTRATION',
    type: 'JP',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '636102', name_en: 'SUPPORT COVID-19', type: 'JP', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '636110',
    name_en: 'ADMINISTRATION (PU)',
    type: 'JP',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636111',
    name_en: 'ADMINISTRATION (ACC)',
    type: 'JP',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636112',
    name_en: 'GM OF ADMINISTRATION (PU) FOR LABOR COST',
    type: 'JP',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626051',
    name_en: 'COMMON EF ACTIVITY : QUALITY',
    type: 'Pillar - Quality',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626052',
    name_en: 'SDM EF ACTIVITY : QUALITY',
    type: 'Pillar - Quality',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626061',
    name_en: 'COMMON EF ACTIVITY : SAFETY',
    type: 'Pillar - Safety',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626062',
    name_en: 'SDM EF ACTIVITY : SAFETY',
    type: 'Pillar - Safety',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626071',
    name_en: 'COMMON EF ACTIVITY : DELIVERY',
    type: 'Pillar - Delivery',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626072',
    name_en: 'SDM EF ACTIVITY : DELIVERY',
    type: 'Pillar - Delivery',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636081',
    name_en: 'COMMON EF ACTIVITY : HRD',
    type: 'Pillar - HRD',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636082',
    name_en: 'COMMON EF ACTIVITY : ATTRACTIVE COMPANY',
    type: 'Pillar - Attractive',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636083',
    name_en: 'COMMON EF ACTIVITY : GOVERNANCE',
    type: 'Pillar - Governance',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636120',
    name_en: 'ACCOUNING & PLANNING COMMON',
    type: 'ACC',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636121',
    name_en: 'ACCOUNING & PLANNING SDM',
    type: 'ACC',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636122',
    name_en: 'ACCOUNING & PLANNING DIESEL',
    type: 'ACC',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636123',
    name_en: 'ACCOUNING & PLANNING GASOLINE',
    type: 'ACC',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636124',
    name_en: 'ACCOUNING & PLANNING SKD',
    type: 'ACC',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '636130', name_en: 'PURCHASING COMMON', type: 'PU', company: 'IND' },
  { dept_code: 'SDM', dept_id: '636131', name_en: 'PURCHASING SDM', type: 'PU', company: 'IND' },
  { dept_code: 'SDM', dept_id: '636132', name_en: 'PURCHASING DIESEL', type: 'PU', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '636133',
    name_en: 'PURCHASING GASOLINE',
    type: 'PU',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '636134', name_en: 'PURCHASING SKD', type: 'PU', company: 'IND' },
  { dept_code: 'SDM', dept_id: '636136', name_en: 'PURCHASING FZ', type: 'PU', company: 'IND' },
  { dept_code: 'SDM', dept_id: '636139', name_en: 'CORPS DT PRO', type: 'CORP', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '636150',
    name_en: 'GENERAL AFFAIR COMMON',
    type: 'GA & CSR',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636151',
    name_en: 'GENERAL AFFAIR SDM',
    type: 'GA & CSR',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636152',
    name_en: 'GENERAL AFFAIR PLANT EXPANSION',
    type: 'GA & CSR',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636154',
    name_en: 'GENERAL AFFAIR SKD',
    type: 'GA & CSR',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636144',
    name_en: 'GENERAL AFFAIR AS&HC COMMON',
    type: 'AR&AS',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636145',
    name_en: 'GENERAL AFFAIR AS&HC SDM.',
    type: 'AR&AS',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636146',
    name_en: 'GENERAL AFFAIR VALIABLE AS&HC COMMON',
    type: 'AR&AS',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636147',
    name_en: 'GENERAL AFFAIR VALIABLE AS&HC SDM',
    type: 'AR&AS',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636180',
    name_en: 'INN SYSTEM DEVELOPMENT COMMON',
    type: 'GA & CSR',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636181',
    name_en: 'INN SYSTEM DEVELOPMENT SDM',
    type: 'GA & CSR',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636159',
    name_en: 'SOCIAL CONTRIBUTION DT PO',
    type: 'GA & CSR',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636140',
    name_en: 'HR ASSOCIATE RELATION COMMON',
    type: 'AR&AS',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636141',
    name_en: 'HR ASSOCIATE RELATION SDM',
    type: 'AR&AS',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636160',
    name_en: 'HR ACTIVITY DEVELOPMENT COMMON',
    type: 'AR&AS',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636170',
    name_en: 'HR RECRUITMENT & SELECTION COMMON',
    type: 'MP Planning/Recruit',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636171',
    name_en: 'HR RECRUITMENT & SELECTION SDM',
    type: 'MP Planning/Recruit',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636174',
    name_en: 'HR RECRUITMENT & SELECTION SKD',
    type: 'MP Planning/Recruit',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636190',
    name_en: 'HR SKILL&MIND DEVELOPMENT COMMON',
    type: 'HRD',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636191',
    name_en: 'HR SKILL&MIND DEVELOPMENT SDM',
    type: 'HRD',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636194',
    name_en: 'HR SKILL&MIND DEVELOPMENT SKD',
    type: 'HRD',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636183',
    name_en: 'HR COMPENSATION & BENEFITS COMMON',
    type: 'C&B and PM',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636184',
    name_en: 'HR COMPENSATION & BENEFITS SDM',
    type: 'C&B and PM',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626500',
    name_en: 'QA QUALITY ASSURANCE PLANNING',
    type: 'QA',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626501',
    name_en: 'QA BKD GROUP &AUDIT CLEANLINESS',
    type: 'QA',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626502',
    name_en: 'QA QUALITY ASSURANCE DIESEL',
    type: 'QA',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626503',
    name_en: 'QA QUALITY ASSURANCE GASOLINE',
    type: 'QA',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636504',
    name_en: 'QA QUALITY ASSURANCE SKD',
    type: 'QA',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626505',
    name_en: 'QA QUALITY ASSURANCE INVESTIGATION',
    type: 'QA',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626506',
    name_en: 'QA QUALITY ASSURANCE G4S',
    type: 'QA',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626507',
    name_en: 'QA QUALITY ASSURANCE GDP',
    type: 'QA',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626508',
    name_en: 'QA QUALITY ASSURANCE FZ',
    type: 'QA',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626519',
    name_en: 'QA QUALITY ASSURANCE HP5E',
    type: 'QA',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626509',
    name_en: 'QA QUALITY ASSURANCE PLANT EXPANSION',
    type: 'QA',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626510',
    name_en: 'QA PRODUCTS INS COMMON',
    type: 'QA',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616551',
    name_en: 'QA PRODUCTS INS DIESEL',
    type: 'QA-PDI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616552',
    name_en: 'QA PRODUCTS INS GASOLINE',
    type: 'QA-PDI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '636554',
    name_en: 'QA PRODUCTS INS SKD',
    type: 'QA-PDI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616553',
    name_en: 'QA PRODUCTS INS GAS&SKD',
    type: 'QA-PDI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '626516',
    name_en: 'QA PRODUCTS INS PLANT EXPANSION',
    type: 'QA-PDI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '626520',
    name_en: 'QA PARTS INS COMMON',
    type: 'QA',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626511',
    name_en: 'DIESEL ELECTRIC FAILURE',
    type: 'QA',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626512',
    name_en: 'GASOLINE ELECTRIC FAILURE',
    type: 'QA',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626513',
    name_en: 'QA PARTS INS SORTING',
    type: 'QA-Sorting',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616561',
    name_en: 'QA PARTS INS DIESEL',
    type: 'QA-PI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616562',
    name_en: 'QA PARTS INS GASOLINE',
    type: 'QA-PI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '636564',
    name_en: 'QA PARTS INS SKD',
    type: 'QA-PI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616565',
    name_en: 'QA PARTS INS GAS&SKD',
    type: 'QA-PI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616563',
    name_en: 'QA PARTS INS COMMON',
    type: 'QA-PI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616566',
    name_en: 'QA PARTS INS G4S',
    type: 'QA-PI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616567',
    name_en: 'QA PARTS INS GDP',
    type: 'QA-PI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616568',
    name_en: 'QA PARTS INS UC',
    type: 'QA-PI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616571',
    name_en: 'QA PARTS INS FZ',
    type: 'QA-PI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616569',
    name_en: 'QA PARTS INS HP5E',
    type: 'QA-PI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '626530',
    name_en: 'QA PARTS INS PLANT EXPANSION',
    type: 'QA-PI',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '626201',
    name_en: 'ED OF MANUFACTURING',
    type: 'JP',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626305',
    name_en: 'PE SUPPLIER DEVELOPMANT',
    type: 'SQA',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '626300', name_en: 'DIE PE COMMON', type: 'PE', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '626301',
    name_en: 'COST DOWN ACTIVITY',
    type: 'PE',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '626302', name_en: 'DIE PE G4S', type: 'PE', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '626303',
    name_en: 'DIE PE PLANT EXPANSION',
    type: 'PE',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '626304', name_en: 'DIE PE HP5E', type: 'PE', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626310', name_en: 'DIE PE HP3', type: 'PE', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626320', name_en: 'DIE PE G2', type: 'PE', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626330', name_en: 'DIE PE RC', type: 'PE', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626400', name_en: 'GAS PE COMMON', type: 'PE', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '626401',
    name_en: 'GAS PE PLANT EXPANSION',
    type: 'PE',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '626410', name_en: 'GAS PE UC', type: 'PE', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626421', name_en: 'GAS PE GDP', type: 'PE', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626010', name_en: 'PROD COMMON', type: 'SPD', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626075', name_en: 'PROD COMMON SDM', type: 'SPD', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '626215',
    name_en: 'RECEIVING CENTER',
    type: 'RECEIVING CENTER',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626390',
    name_en: 'DIE PD F1 STAFF',
    type: 'PD Staff',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616350',
    name_en: 'DIE PD F1 P1 HP3 ASSY',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616351',
    name_en: 'DIE PD F1 P1 HP3 INS',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616344',
    name_en: 'HP5 ASSEMBLING',
    type: 'PD2 HP5',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616345',
    name_en: 'HP5 INSPECTION',
    type: 'PD2 HP5',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616976',
    name_en: 'HP5E ASSEMBLING',
    type: 'PD2 HP5E',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616977',
    name_en: 'HP5E INSPECTION',
    type: 'PD2 HP5E',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616352',
    name_en: 'DIE PD F1 P1 RC ASSY',
    type: 'PD2 RC',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616353',
    name_en: 'DIE PD F1 P1 SCV ASSY',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616354',
    name_en: 'DIE PD F1 P2 RC TAPPING',
    type: 'PD2 RC',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616356',
    name_en: 'DIE PD F1 P2 RC ECM',
    type: 'PD2 RC',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616355',
    name_en: 'DIE PD F1 P2 HP3 HOUSING',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616360',
    name_en: 'DIE PD F1 P2 HP3 CAMSHAFT',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616364',
    name_en: 'DIE PD F1 P2 HP3 RING CAM',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616365',
    name_en: 'DIE PD F1 P2 HP3 COVER PUMP',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616361',
    name_en: 'DIEPDF1P2 SCV CAUKING &',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616366',
    name_en: 'DIE PD F1 P2 SCV HOUSING',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616367',
    name_en: 'DIE PD F1 P2 SCV NEEDLE',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616362',
    name_en: 'DIE PD F1 P2 HP3 CYLINDER',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616368',
    name_en: 'DIE PD F1 P2 HP3 CYLINDER',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616373',
    name_en: 'DIE PD F1 P2 HP3 CYLINDER ROPE LAP',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616369',
    name_en: 'DIE PD F1 P2 HP3 PLUNGER',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616357',
    name_en: 'DIE PDF1 P2 HP3 SEAT/VAL',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616363',
    name_en: 'DIE PD F1 P2 HP3 ELEMENT',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616358',
    name_en: 'DIE PDF1 P2 HP3 SEAT/VAL',
    type: 'PD2 HP3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616359',
    name_en: 'DIE PD F1 P2 HP3 MEASUREM',
    type: 'MSM',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616377',
    name_en: 'DIE PD F1 P2 RC GUIDE SPRING',
    type: 'PD2 RC',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616392',
    name_en: 'DIE PD F1 P2 RC AUTOFRETTAGE',
    type: 'PD2 RC',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616340',
    name_en: 'DIE PD F1 P2 WASHING',
    type: 'PD2 Washing PUMP',
    company: 'DIR',
  },
  { dept_code: 'SDM', dept_id: '616346', name_en: 'HP5 HOUSING', type: 'PD2 HP5', company: 'DIR' },
  {
    dept_code: 'SDM',
    dept_id: '616347',
    name_en: 'HP5 CAM SHAFT',
    type: 'PD2 HP5',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616348',
    name_en: 'HP5 CYLINDER GRINDING',
    type: 'PD2 HP5',
    company: 'DIR',
  },
  { dept_code: 'SDM', dept_id: '616349', name_en: 'HP5 PLUNGER', type: 'PD2 HP5', company: 'DIR' },
  {
    dept_code: 'SDM',
    dept_id: '616950',
    name_en: 'HP5 CYLINDER ECM',
    type: 'PD2 HP5',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616951',
    name_en: 'HP5 CYLINDER SHORT PEENING',
    type: 'PD2 HP5',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616952',
    name_en: 'HP5 SHOE GRINDING',
    type: 'PD2 HP5',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616953',
    name_en: 'HP5 ROLLER GRINDING',
    type: 'PD2 HP5',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616311',
    name_en: 'HP5 BODY TAPPET',
    type: 'PD2 HP5',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616312',
    name_en: 'HP5 ELEMENT MATCHING',
    type: 'PD2 HP5',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616970',
    name_en: 'HP5E CYLINDER MACHINING & ECM',
    type: 'PD2 HP5E',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616971',
    name_en: 'HP5E CYLINDER SHORT PEENING',
    type: 'PD2 HP5E',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616972',
    name_en: 'HP5E CYLINDER GRINDING',
    type: 'PD2 HP5E',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616973',
    name_en: 'HP5E PLUNGER GRINDING',
    type: 'PD2 HP5E',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616974',
    name_en: 'HP5E LAPPING AFTER COATING',
    type: 'PD2 HP5E',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616975',
    name_en: 'HP5E ELEMENT',
    type: 'PD2 HP5E',
    company: 'DIR',
  },
  { dept_code: 'SDM', dept_id: '616978', name_en: 'HP5E TAPPET', type: 'PD2 HP5E', company: 'DIR' },
  {
    dept_code: 'SDM',
    dept_id: '616979',
    name_en: 'HP5E TAPPET GRINDING',
    type: 'PD2 HP5E',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616980',
    name_en: 'HP5E PULSATION DAMPER ASSEMBLY',
    type: 'PD2 HP5E',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616394',
    name_en: 'HP C CAM SHAFT',
    type: 'PD2 HP5',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616395',
    name_en: 'HP C CYLINDER',
    type: 'PD2 HP5',
    company: 'DIR',
  },
  { dept_code: 'SDM', dept_id: '616396', name_en: 'HP C PLUNGER', type: 'PD2 HP5', company: 'DIR' },
  {
    dept_code: 'SDM',
    dept_id: '616313',
    name_en: 'HP C BODY TAPPET',
    type: 'PD2 HP5',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616314',
    name_en: 'HP C ELEMENT MATCHING',
    type: 'PD2 HP5',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616341',
    name_en: 'DIE PD F1 P2 PREGNANT',
    type: 'PREGNANT',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '626391',
    name_en: 'DIE PD F2 STAFF',
    type: 'PD Staff',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616370',
    name_en: 'DIE PD F2 P3 G2 ASSY1',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616371',
    name_en: 'DIE PD F2 P3 G3 ASSY2',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616372',
    name_en: 'DIE PD F2 P3 PRVⅡ ASSY',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616397',
    name_en: 'DIE PD F2 P3 G4 ASSY',
    type: 'PD1 G4',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616376',
    name_en: 'DIE PD F2 P3 G2 INS1',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616374',
    name_en: 'DIE PD F2 P3 G3 INS2',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616375',
    name_en: 'DIE PD F2 P3 INJ SUIJUN',
    type: 'MSM',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616398',
    name_en: 'DIE PD F2 P3 G4 INS',
    type: 'PD1 G4',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616379',
    name_en: 'DIE PD F2 P4 G2C L/B EDM',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616380',
    name_en: 'DIE PD F2 P4 G2C L/B GRINDING',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616381',
    name_en: 'DIE PD F2 P4 G2C L/B HORNING',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616384',
    name_en: 'DIE PD F2 P4 G2C MATCHING',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616385',
    name_en: 'DIE PD F2 P4 G2C PISTON GR',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616389',
    name_en: 'DIE PD F2 P4 PRV 2 GRINDING',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616382',
    name_en: 'DIE PD F2 P4 G2C ORIFICE GR',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616383',
    name_en: 'DIE PD F2 P4 G2C ORIFICE IN',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616387',
    name_en: 'DIE PD F2 P4 G2C ORIFICE OUT',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616386',
    name_en: 'DIE PD F2 P4 G2C VALVE GR',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616388',
    name_en: 'DIE PD F2 P4 G2C ARMTURE GR',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616342',
    name_en: 'DIE PD F2 P4 G2C PREGNANT',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616901',
    name_en: 'DIE PD F2 P4 G3 VALVE EDM',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616902',
    name_en: 'DIE PD F2 P4 G3 L/B EDM',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616903',
    name_en: 'DIE PD F2 P4 G3 L/B GRINDING',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616904',
    name_en: 'DIE PD F2 P4 G3 L/B HORNING',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616905',
    name_en: 'DIE PD F2 P4 G3 MATCHING',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616906',
    name_en: 'DIE PD F2 P4 G3 PISTON GR',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616907',
    name_en: 'DIE PD F2 P4 G3 ORIFICE GR',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616908',
    name_en: 'DIE PD F2 P4 G3 ORIFICE IN',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616909',
    name_en: 'DIE PD F2 P4 G3 ORIFICE OUT',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616910',
    name_en: 'DIE PD F2 P4 G3 VALVE GR',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616911',
    name_en: 'DIE PD F2 P4 G3 ARMTURE GR',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616938',
    name_en: 'DIE PD F2 P4 G3 INLET CONNECTOR',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616912',
    name_en: 'DIE PD F2 P4 G2 VALVE EDM',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616913',
    name_en: 'DIE PD F2 P4 G2 L/B EDM',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616914',
    name_en: 'DIE PD F2 P4 G2 L/B GRINDING',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616915',
    name_en: 'DIE PD F2 P4 G2 L/B HORNING',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616916',
    name_en: 'DIE PD F2 P4 G2 MATCHING',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616917',
    name_en: 'DIE PD F2 P4 G2 PISTON GR',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616918',
    name_en: 'DIE PD F2 P4 G2 ORIFICE GR',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616919',
    name_en: 'DIE PD F2 P4 G2 ORIFICE IN',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616920',
    name_en: 'DIE PD F2 P4 G2 ORIFICE OUT',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616921',
    name_en: 'DIE PD F2 P4 G2 VALVE GR',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616922',
    name_en: 'DIE PD F2 P4 G2 ARMTURE GR',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616924',
    name_en: 'G4 INJ LOWER BODY ECM',
    type: 'PD1 G4',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616925',
    name_en: 'G4 INJ LOWER BODY GRINDING',
    type: 'PD1 G4',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616926',
    name_en: 'G4 INJ ORIFICE GRINDING',
    type: 'PD1 G4',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616927',
    name_en: 'G4 INJ ORIFICE AFM',
    type: 'PD1 G4',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616928',
    name_en: 'G4 INJ ORIFICE CUTTING',
    type: 'PD1 G4',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616939',
    name_en: 'G4 INJ CONTROL PLATE GRINDING',
    type: 'PD1 G4',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616940',
    name_en: 'G4 INJ CONTROL PLATE AFM',
    type: 'PD1 G4',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616929',
    name_en: 'G4 INJ VALVE GRINDING',
    type: 'PD1 G4',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616930',
    name_en: 'G4 INJ ARMATURE GRINDING',
    type: 'PD1 G4',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616931',
    name_en: 'G4 INJ ORIFICE LAPPING',
    type: 'PD1 G4',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616932',
    name_en: 'INJ C LOWER BODY GRINDING',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616933',
    name_en: 'INJ C ORIFICE GRINDING',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616934',
    name_en: 'INJ C ORIFICE IN',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616935',
    name_en: 'INJ C ORIFICE OUT',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616936',
    name_en: 'INJ C VALVE GRINDING',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616937',
    name_en: 'INJ C ARMATURE GRINDING',
    type: 'PD1 G2&G3',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616960',
    name_en: 'DIE PD F1 P2 WASHING',
    type: 'PD1 Washing INJ',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616923',
    name_en: 'DIE PD COMMON G4S',
    type: 'PD Staff',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626430',
    name_en: 'GAS PD (STAFF) - COMMON',
    type: 'PD Staff',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626431',
    name_en: 'GAS PD (STAFF) - UC',
    type: 'PD Staff',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626432',
    name_en: 'GAS PD (STAFF) - GDP',
    type: 'PD Staff',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616440',
    name_en: 'GAS PD P5 ASSY UC 1ST LINE',
    type: 'PD3 UC',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616441',
    name_en: 'GAS PD P6 ASSY UC 2ND LINE',
    type: 'PD3 UC',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616442',
    name_en: 'UC NEEDLE ROUGH',
    type: 'PD3 UC',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616443',
    name_en: 'UC BODY GRINDING',
    type: 'PD3 UC',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616444',
    name_en: 'UC PIPE GRINDING',
    type: 'PD3 UC',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616445',
    name_en: 'UC CONNECTOR GRINDING',
    type: 'PD3 UC',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616446',
    name_en: 'UC NEEDLE FINISHED',
    type: 'PD3 UC',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616343',
    name_en: 'GAS PD P6 PREGNANT',
    type: 'PREGNANT',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616451',
    name_en: 'GDP ASSEMBLING',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616452',
    name_en: 'GDP INSPECTION',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  { dept_code: 'SDM', dept_id: '616466', name_en: 'GDP WASHING', type: 'PD3 GDP', company: 'DIR' },
  {
    dept_code: 'SDM',
    dept_id: '616467',
    name_en: 'GDP SOLENOID ASSY',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  { dept_code: 'SDM', dept_id: '616468', name_en: 'GDP COATING', type: 'PD3 GDP', company: 'DIR' },
  {
    dept_code: 'SDM',
    dept_id: '616469',
    name_en: 'GDP AFTER COATING',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  { dept_code: 'SDM', dept_id: '616450', name_en: 'GAS MEASUREMENT', type: 'MSM', company: 'DIR' },
  { dept_code: 'SDM', dept_id: '616453', name_en: 'GDP HEAD 3W', type: 'PD3 GDP', company: 'DIR' },
  {
    dept_code: 'SDM',
    dept_id: '616454',
    name_en: 'GDP PLUNGER GRINDING',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616455',
    name_en: 'GDP DELIVERY VALVE GRINDING',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616456',
    name_en: 'GDP SUCTION VALVE GRINDING',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616457',
    name_en: 'GDP RELIEF VALVE GRINDING',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616458',
    name_en: 'GDP CONNECTOR SUB ASSY',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616459',
    name_en: 'GDP ARMATURE GRINDING',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616460',
    name_en: 'GDP ROD ARMATURE GRINDING',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616461',
    name_en: 'GDP GUIDE ARMATURE GRINDING',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616462',
    name_en: 'GDP STATOR GRINDING',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616463',
    name_en: 'GDP ELEMENT SUB ASSY',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616464',
    name_en: 'GDP HEAD GRINDING',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '616465',
    name_en: 'GDP PLUNGER LAPPING',
    type: 'PD3 GDP',
    company: 'DIR',
  },
  {
    dept_code: 'SDM',
    dept_id: '626600',
    name_en: 'PC PLANNING COMMON',
    type: 'PC',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '626601', name_en: 'PC PLANNING SDM', type: 'PC', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '626602',
    name_en: 'PC PLANNING DIESEL SDM&SKD',
    type: 'PC',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626603',
    name_en: 'PC PLANNING GASOLINE SDM&SKD',
    type: 'PC',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '636604', name_en: 'PC PLANNING SKD', type: 'PC', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626605', name_en: 'PC PLANNING G4S', type: 'PC', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626606', name_en: 'PC PLANNING GDP', type: 'PC', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626607', name_en: 'PC PLANNING FZ', type: 'PC', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '626608',
    name_en: 'PC PLANNING PLANT EXPANSION',
    type: 'PC',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626610',
    name_en: 'PC LOGISTICS COMMON',
    type: 'WH IND',
    company: 'DIR',
  },
  { dept_code: 'SDM', dept_id: '626611', name_en: 'PC LOGISTICS SDM', type: 'PC', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '626612',
    name_en: 'PC LOGISTICS DIESEL',
    type: 'PC',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '626613', name_en: 'PC LOGISTICS UC', type: 'PC', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626615', name_en: 'PC LOGISTICS GDP', type: 'PC', company: 'IND' },
  { dept_code: 'SDM', dept_id: '636614', name_en: 'PC LOGISTICS SKD', type: 'PC', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '616650',
    name_en: 'PC MATECON. COMMON',
    type: 'WH',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '616651', name_en: 'PC MATECON. SDM', type: 'WH', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '616652',
    name_en: 'PC MATECON. DIESEL',
    type: 'WH',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '616656', name_en: 'PC MATECON. G4S', type: 'WH', company: 'IND' },
  { dept_code: 'SDM', dept_id: '616653', name_en: 'PC MATECON. UC', type: 'WH', company: 'IND' },
  { dept_code: 'SDM', dept_id: '616655', name_en: 'PC MATECON. GDP', type: 'WH', company: 'IND' },
  { dept_code: 'SDM', dept_id: '636654', name_en: 'PC MATECON. SKD', type: 'WH', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '616660',
    name_en: 'PC PACKAGING COMMON',
    type: 'WH',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '616661', name_en: 'PC PACKAGING SDM', type: 'WH', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '616662',
    name_en: 'PC PACKAGING DIESEL',
    type: 'WH',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '616666', name_en: 'PC PACKAGING G4S', type: 'WH', company: 'IND' },
  { dept_code: 'SDM', dept_id: '616663', name_en: 'PC PACKAGING UC', type: 'WH', company: 'IND' },
  { dept_code: 'SDM', dept_id: '616665', name_en: 'PC PACKAGING GDP', type: 'WH', company: 'IND' },
  { dept_code: 'SDM', dept_id: '636664', name_en: 'PC PACKAGING SKD', type: 'WH', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '616670',
    name_en: 'PC SHIPPING COMMON',
    type: 'WH',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '616671', name_en: 'PC SHIPPING SDM', type: 'WH', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '616672',
    name_en: 'PC SHIPPING DIESEL',
    type: 'WH',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '616673', name_en: 'PC SHIPPING UC', type: 'WH', company: 'IND' },
  { dept_code: 'SDM', dept_id: '616675', name_en: 'PC SHIPPING GDP', type: 'WH', company: 'IND' },
  { dept_code: 'SDM', dept_id: '616676', name_en: 'PC SHIPPING G4S', type: 'WH', company: 'IND' },
  { dept_code: 'SDM', dept_id: '616677', name_en: 'PC PLANNING FZ', type: 'WH', company: 'IND' },
  { dept_code: 'SDM', dept_id: '636674', name_en: 'PC SHIPPING SKD', type: 'WH', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626700', name_en: 'EF TIE COMMON', type: 'TIE', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626701', name_en: 'EF TIE KAIZEN', type: 'TIE', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626702', name_en: 'EF TIE G2 INJ', type: 'TIE', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626703', name_en: 'EF TIE HP3 PUMP', type: 'TIE', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626716', name_en: 'EF TIE HP5 PUMP', type: 'TIE', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626717', name_en: 'EF TIE G4 INJ', type: 'TIE', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626704', name_en: 'EF TIE RAIL', type: 'TIE', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626705', name_en: 'EF TIE WASHING', type: 'TIE', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626706', name_en: 'EF TIE UC-INJ', type: 'TIE', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626707', name_en: 'EF TIE GDP', type: 'TIE', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '636715',
    name_en: 'EF TIE SKD DIESEL',
    type: 'TIE',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636708',
    name_en: 'EF TIE SKD GASOLINE',
    type: 'TIE',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '626709', name_en: 'EF TIE LOGISTICS', type: 'TIE', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '626718',
    name_en: 'EF TIE PLANT EXPANSION',
    type: 'Special',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626719',
    name_en: 'SUPPORT WIN-WIN ACTIVITY',
    type: 'Special',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626720',
    name_en: 'FE SAFETY & ENVIRONMENT COMMON',
    type: 'SE',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626721',
    name_en: 'FE SAFETY & ENVIRONMENT SDM',
    type: 'SE',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636724',
    name_en: 'FE SAFETY & ENVIRONMENT SKD',
    type: 'SE',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626725',
    name_en: 'FE SAFETY & ENVIRONMENT PLANT EXPANSION',
    type: 'SE',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626850',
    name_en: 'MT MAINTENANCE CENTER COMMON',
    type: 'MT',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626800',
    name_en: 'MT MAINTENANCE DIE COMMON',
    type: 'MT',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626810',
    name_en: 'MT MAINTENANCE GAS',
    type: 'MT',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '636820',
    name_en: 'MT MAINTENANCE SKD COMMON',
    type: 'MT',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '626821', name_en: 'MT MAINTENANCE G4', type: 'MT', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '626822',
    name_en: 'MT MAINTENANCE GDP',
    type: 'MT',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '626830',
    name_en: 'MT FACILITY COMMON',
    type: 'FAC',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '626831', name_en: 'MT FACILITY SDM', type: 'FAC', company: 'IND' },
  { dept_code: 'SDM', dept_id: '636834', name_en: 'MT FACILITY SKD', type: 'FAC', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626880', name_en: 'MT TPM COMMON', type: 'MT', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '616030',
    name_en: 'MACHINE MAINTENANCE COST HP3',
    type: 'MC cost',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616031',
    name_en: 'MACHINE MAINTENANCE COST HP5',
    type: 'MC cost',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616032',
    name_en: 'MACHINE MAINTENANCE COST RAIL',
    type: 'MC cost',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616033',
    name_en: 'MACHINE MAINTENANCE COST G2',
    type: 'MC cost',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616034',
    name_en: 'MACHINE MAINTENANCE COST G3',
    type: 'MC cost',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616035',
    name_en: 'MACHINE MAINTENANCE COST G4',
    type: 'MC cost',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616036',
    name_en: 'MACHINE MAINTENANCE COST UC',
    type: 'MC cost',
    company: 'IND',
  },
  {
    dept_code: 'SDM',
    dept_id: '616037',
    name_en: 'MACHINE MAINTENANCE COST GD-P3S',
    type: 'MC cost',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '626840', name_en: 'TOOL ROOM COMMON', type: 'MT', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '646860',
    name_en: 'IHM JIG SHOP COMMON',
    type: 'MT',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '646870', name_en: 'IHM KAIZEN COMMON', type: 'MT', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: '626844',
    name_en: 'IHM MOLD & DIE REPAIR COMMON',
    type: 'MT',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: '626845', name_en: 'REPAIR SPARE PART', type: 'MT', company: 'IND' },
  { dept_code: 'SDM', dept_id: '626846', name_en: 'OVERHUAL', type: 'MT', company: 'IND' },
  {
    dept_code: 'SDM',
    dept_id: 'ENV001',
    name_en: 'Environment',
    type: 'Environment',
    company: 'IND',
  },
  { dept_code: 'SDM', dept_id: 'HRD001', name_en: 'SPD-HRD', type: 'SPD-HRD', company: 'IND' },
];

const SKD_DEPARTMENTS = [
  { dept_code: 'SKD', dept_id: '737900', name_en: 'MD OF SKD', type: 'CPC', company: 'IND' },
  { dept_code: 'SKD', dept_id: '737902', name_en: 'COMMUNICATION', type: 'CPC', company: 'IND' },
  { dept_code: 'SKD', dept_id: '737903', name_en: 'CPC', type: 'CPC', company: 'IND' },
  {
    dept_code: 'SKD',
    dept_id: '727904',
    name_en: 'GENERAL MANUFACTURING',
    type: 'CPC',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727910',
    name_en: 'PE GM, AGM, OFFICER',
    type: 'PE',
    company: 'IND',
  },
  { dept_code: 'SKD', dept_id: '727911', name_en: 'FF CURRENT MODEL', type: 'PE', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727811', name_en: 'FF NEW MODEL', type: 'PE', company: 'IND' },
  {
    dept_code: 'SKD',
    dept_id: '727940',
    name_en: 'DIESEL CURRENT MODEL',
    type: 'PE',
    company: 'IND',
  },
  { dept_code: 'SKD', dept_id: '727941', name_en: 'DIESEL NEW MODEL', type: 'PE', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727822', name_en: 'MACHINERY', type: 'PE', company: 'IND' },
  {
    dept_code: 'SKD',
    dept_id: '727821',
    name_en: 'MS COMMON (SAFETY)',
    type: 'SAFETY',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727954',
    name_en: 'PRODUCTIVITY IMPROVEMENT',
    type: 'SPD',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727955',
    name_en: 'PD.COMMON TOP MANAGEMENT',
    type: 'SPD',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727951',
    name_en: 'PD MANAGEMENT VALE_PD6',
    type: 'SPD',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727952',
    name_en: 'PD MANAGEMENT SOL_PD7',
    type: 'SPD',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727953',
    name_en: 'PD MANAGEMENT FF_PD8',
    type: 'SPD',
    company: 'IND',
  },
  { dept_code: 'SKD', dept_id: '727820', name_en: 'PD COMMON', type: 'SPD', company: 'IND' },
  {
    dept_code: 'SKD',
    dept_id: '717960',
    name_en: 'PD FF SIFS ASSY',
    type: 'PD 5 DF & SIFS',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717961',
    name_en: 'PD FF SIFS PUMP UNIT',
    type: 'PD 5 DF & SIFS',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717962',
    name_en: 'PD FF SIFS FILTER ASSY',
    type: 'PD 5 DF & SIFS',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717963',
    name_en: 'PD FF SIFS SUCTION',
    type: 'PD 5 DF & SIFS',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717965',
    name_en: 'PD FF MOTORCYCLE SIFS',
    type: 'PD 5 DF & SIFS',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717970',
    name_en: 'DF RESIN',
    type: 'PD 5 DF & SIFS',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717517',
    name_en: 'DF ASSY (5F00)',
    type: 'PD 5 DF & SIFS',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717518',
    name_en: 'DF SUB ASSY',
    type: 'PD 5 DF & SIFS',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717519',
    name_en: 'SUB ASSY 5F00',
    type: 'PD 5 DF & SIFS',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717971',
    name_en: 'WINDING',
    type: 'PD 5 DF & SIFS',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717972',
    name_en: 'ELEMENT SA',
    type: 'PD 5 DF & SIFS',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717520',
    name_en: 'PACKING EM',
    type: 'PD 5 DF & SIFS',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717980',
    name_en: 'SOLENOID ASSY',
    type: 'PD 4 SOL',
    company: 'DIR',
  },
  { dept_code: 'SKD', dept_id: '717510', name_en: 'PMP', type: 'PD 4 SOL', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717982', name_en: 'FUSING', type: 'PD 4 SOL', company: 'DIR' },
  {
    dept_code: 'SKD',
    dept_id: '717511',
    name_en: 'COIL BUSH ASSEMBLY',
    type: 'PD 4 SOL',
    company: 'DIR',
  },
  { dept_code: 'SKD', dept_id: '717512', name_en: 'EPOPXY MOLD', type: 'PD 4 SOL', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717513', name_en: 'WASHING', type: 'PD 4 SOL', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717988', name_en: 'ASSY G4', type: 'PD 4 SOL', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717514', name_en: 'ASSY G4.5', type: 'PD 4 SOL', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717515', name_en: 'TERMINAL', type: 'PD 4 SOL', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717516', name_en: 'WASHING G4', type: 'PD 4 SOL', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717521', name_en: 'S/A G4', type: 'PD 4 SOL', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717522', name_en: 'S/A G4.5', type: 'PD 4 SOL', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717983', name_en: 'SCV ASSY', type: 'PD 4 VALVE', company: 'DIR' },
  {
    dept_code: 'SKD',
    dept_id: '717505',
    name_en: 'MAGNET S/A',
    type: 'PD 4 VALVE',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717504',
    name_en: 'MAGNET SV2',
    type: 'PD 4 VALVE',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717984',
    name_en: 'BODY VALVE SUB ASSY',
    type: 'PD 4 VALVE',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717500',
    name_en: 'VALVE SUB ASSY NORMAL',
    type: 'PD 4 VALVE',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717501',
    name_en: 'VALVE SUB ASSY DLC',
    type: 'PD 4 VALVE',
    company: 'DIR',
  },
  { dept_code: 'SKD', dept_id: '717502', name_en: 'HOUSING', type: 'PD 4 VALVE', company: 'DIR' },
  {
    dept_code: 'SKD',
    dept_id: '717503',
    name_en: 'WASHING SCV',
    type: 'PD 4 VALVE',
    company: 'DIR',
  },
  { dept_code: 'SKD', dept_id: '717985', name_en: 'PCV ASSY', type: 'PD 4 VALVE', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717986', name_en: 'PRV ASSY', type: 'PD 4 VALVE', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717987', name_en: 'BODY 4W', type: 'PD 4 VALVE', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717506', name_en: 'BODY SA', type: 'PD 4 VALVE', company: 'DIR' },
  {
    dept_code: 'SKD',
    dept_id: '717507',
    name_en: 'ARMATURE SA',
    type: 'PD 4 VALVE',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717508',
    name_en: 'SOLENOID SA',
    type: 'PD 4 VALVE',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717509',
    name_en: 'WASHING PCV,PRV',
    type: 'PD 4 VALVE',
    company: 'DIR',
  },
  { dept_code: 'SKD', dept_id: '717959', name_en: 'PD MEASUREMENT', type: 'MEA', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '727990', name_en: 'QA SIFS', type: 'QA', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727991', name_en: 'QA DF', type: 'QA', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727992', name_en: 'QA SOL', type: 'QA', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727993', name_en: 'QA COMMON', type: 'QA', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727994', name_en: 'QA SCV', type: 'QA', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727924', name_en: 'QA PCV PRV', type: 'QA', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727925', name_en: 'QA G4', type: 'QA', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727995', name_en: 'PC SIFS', type: 'PC', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727996', name_en: 'PC DF', type: 'PC', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727997', name_en: 'PC SOL', type: 'PC', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727998', name_en: 'PC COMMON', type: 'PC', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727999', name_en: 'PC SCV', type: 'PC', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727926', name_en: 'PC PCV PRV', type: 'PC', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727927', name_en: 'PC G4', type: 'PC', company: 'IND' },
  { dept_code: 'SKD', dept_id: '737931', name_en: 'PU DF', type: 'PU', company: 'IND' },
  { dept_code: 'SKD', dept_id: '737932', name_en: 'PU SOL', type: 'PU', company: 'IND' },
  { dept_code: 'SKD', dept_id: '737933', name_en: 'PU COMMON', type: 'PU', company: 'IND' },
  { dept_code: 'SKD', dept_id: '737934', name_en: 'PU SIFS', type: 'PU', company: 'IND' },
  { dept_code: 'SKD', dept_id: '737935', name_en: 'PU SCV', type: 'PU', company: 'IND' },
  {
    dept_code: 'SKD',
    dept_id: '737936',
    name_en: 'PU MOTORCYCLE SIFS',
    type: 'PU',
    company: 'IND',
  },
  { dept_code: 'SKD', dept_id: '737937', name_en: 'PU PCV PRV', type: 'PU', company: 'IND' },
  { dept_code: 'SKD', dept_id: '737938', name_en: 'PU G4', type: 'PU', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727945', name_en: 'QA PART INS SIFS', type: 'PI', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727946', name_en: 'QA PART INS DF', type: 'PI', company: 'IND' },
  { dept_code: 'SKD', dept_id: '727947', name_en: 'QA PART INS SOL', type: 'PI', company: 'IND' },
  {
    dept_code: 'SKD',
    dept_id: '727948',
    name_en: 'QA PART INS COMMON',
    type: 'PI',
    company: 'IND',
  },
  { dept_code: 'SKD', dept_id: '727949', name_en: 'QA PART INS SCV', type: 'PI', company: 'IND' },
  {
    dept_code: 'SKD',
    dept_id: '727944',
    name_en: 'QA PART INS PCV PRV',
    type: 'PI',
    company: 'IND',
  },
  { dept_code: 'SKD', dept_id: '727950', name_en: 'QA PART INS G4', type: 'PI', company: 'IND' },
  {
    dept_code: 'SKD',
    dept_id: '727912',
    name_en: 'QA PRODUCTION INS SIFS',
    type: 'QA (PDI)',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727913',
    name_en: 'QA PRODUCTION INS DF',
    type: 'QA (PDI)',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727914',
    name_en: 'QA PRODUCTION INS SOL&G4',
    type: 'QA (PDI)',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727915',
    name_en: 'QA PRODUCTION INS COMMON',
    type: 'QA (PDI)',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '717823',
    name_en: 'MACHINE MAINTENANCE SOL',
    type: 'MAINTENANCE',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717824',
    name_en: 'MACHINE MAINTENANCE G4',
    type: 'MAINTENANCE',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717825',
    name_en: 'MACHINE MAINTENANCE SCV',
    type: 'MAINTENANCE',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717826',
    name_en: 'MACHINE MAINTENANCE PCV',
    type: 'MAINTENANCE',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717827',
    name_en: 'MACHINE MAINTENANCE PRV',
    type: 'MAINTENANCE',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717828',
    name_en: 'MACHINE MAINTENANCE PCV PRV COMMON',
    type: 'MAINTENANCE',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717829',
    name_en: 'MACHINE MAINTENANCE DF',
    type: 'MAINTENANCE',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717830',
    name_en: 'MACHINE MAINTENANCE SIFS',
    type: 'MAINTENANCE',
    company: 'DIR',
  },
  {
    dept_code: 'SKD',
    dept_id: '717831',
    name_en: 'MOLD DIE PCV PRV COMMON',
    type: 'MOLD',
    company: 'DIR',
  },
  { dept_code: 'SKD', dept_id: '717832', name_en: 'MOLD DIE SOL', type: 'MOLD', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717833', name_en: 'MOLD DIE G4', type: 'MOLD', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717834', name_en: 'MOLD DIE SCV', type: 'MOLD', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717835', name_en: 'MOLD DIE DF', type: 'MOLD', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717836', name_en: 'MOLD DIE SIFS', type: 'MOLD', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717837', name_en: 'PD PREGNANT', type: 'PREGNANT', company: 'DIR' },
  {
    dept_code: 'SKD',
    dept_id: '727894',
    name_en: 'SCV QUALITY PROBLEM',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727895',
    name_en: 'DF QUALITY PROBLEM',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727896',
    name_en: 'PCV PRV QUALITY PROBLEM',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727897',
    name_en: 'SOL QUALITY PROBLEM',
    type: 'Quality issue',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727898',
    name_en: 'AISAN PROJECT',
    type: 'AISAN PROJECT',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727840',
    name_en: 'SKD EF ACTIVITY : SAFETY',
    type: 'EF',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727841',
    name_en: 'SKD EF ACTIVITY : QUALITY',
    type: 'EF',
    company: 'IND',
  },
  {
    dept_code: 'SKD',
    dept_id: '727842',
    name_en: 'SKD EF ACTIVITY : DELIVERY',
    type: 'EF',
    company: 'IND',
  },
  { dept_code: 'SKD', dept_id: '717928', name_en: 'WH Common', type: 'WH', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717929', name_en: 'WH DF', type: 'WH', company: 'DIR' },
  { dept_code: 'SKD', dept_id: '717930', name_en: 'WH SIFS', type: 'WH', company: 'DIR' },
  {
    dept_code: 'SKD',
    dept_id: 'ENV002',
    name_en: 'Environment',
    type: 'Environment',
    company: 'IND',
  },
];

const ALL_DEPARTMENTS = [...SDM_DEPARTMENTS, ...SKD_DEPARTMENTS];

async function seedSpoDepartments(): Promise<void> {
  console.log('='.repeat(80));
  console.log('SPO DEPARTMENTS SEEDING');
  console.log('='.repeat(80));
  console.log(`Server: ${config.server}`);
  console.log(`Database: ${config.database}\n`);

  try {
    const db = await new sql.ConnectionPool(config).connect();

    console.log('Creating departments table if not exists...');

    // Create departments table
    await db.request().query(`
      IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'departments')
      BEGIN
        CREATE TABLE departments (
          id INT IDENTITY(1,1) PRIMARY KEY,
          dept_code NVARCHAR(50) NOT NULL,
          dept_id NVARCHAR(50) NOT NULL UNIQUE,
          name_en NVARCHAR(255) NOT NULL,
          name_th NVARCHAR(255) NULL,
          [type] NVARCHAR(100) NULL,
          company NVARCHAR(100) NULL,
          status NVARCHAR(20) DEFAULT 'Active',
          sort_order INT DEFAULT 0,
          created_at DATETIME DEFAULT GETDATE(),
          updated_at DATETIME DEFAULT GETDATE()
        );
        
        CREATE INDEX IX_departments_dept_id ON departments(dept_id);
        CREATE INDEX IX_departments_dept_code ON departments(dept_code);
        CREATE INDEX IX_departments_status ON departments(status);
      END
    `);

    console.log('Departments table created/verified successfully');

    // Clear existing data
    console.log('Clearing existing departments...');
    await db.request().query('DELETE FROM departments');

    console.log(`Seeding ${ALL_DEPARTMENTS.length} departments from SPO_Dev...`);

    // Insert departments in batches
    const batchSize = 50;
    for (let i = 0; i < ALL_DEPARTMENTS.length; i += batchSize) {
      const batch = ALL_DEPARTMENTS.slice(i, i + batchSize);

      for (const dept of batch) {
        await db
          .request()
          .input('dept_code', sql.NVarChar, dept.dept_code)
          .input('dept_id', sql.NVarChar, dept.dept_id)
          .input('name_en', sql.NVarChar, dept.name_en)
          .input('name_th', sql.NVarChar, null)
          .input('type', sql.NVarChar, dept.type)
          .input('company', sql.NVarChar, dept.company)
          .input('status', sql.NVarChar, 'Active')
          .input('sort_order', sql.Int, Math.floor(i / batchSize) + 1).query(`
            INSERT INTO departments (dept_code, dept_id, name_en, name_th, [type], company, status, sort_order, created_at, updated_at)
            VALUES (@dept_code, @dept_id, @name_en, @name_th, @type, @company, @status, @sort_order, GETDATE(), GETDATE())
          `);
      }

      console.log(
        `Inserted batch ${Math.floor(i / batchSize) + 1}/${Math.ceil(ALL_DEPARTMENTS.length / batchSize)}`
      );
    }

    // Verify count
    const countResult = await db.request().query('SELECT COUNT(*) as count FROM departments');
    console.log(`✅ Successfully seeded ${countResult.recordset[0].count} departments`);

    // Show summary by company
    const summaryResult = await db.request().query(`
      SELECT company, COUNT(*) as count 
      FROM departments 
      GROUP BY company 
      ORDER BY company
    `);

    console.log('\nDepartments by company:');
    for (const row of summaryResult.recordset) {
      console.log(`  ${row.company}: ${row.count} departments`);
    }

    console.log('='.repeat(80));
    console.log('DEPARTMENTS SEEDING COMPLETE');
    console.log('='.repeat(80));
  } catch (error) {
    console.error('Failed to seed departments', error);
    throw error;
  }
}

// Run if called directly
if (require.main === module) {
  seedSpoDepartments()
    .then(() => {
      console.log('Department seeding completed');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Department seeding failed', error);
      process.exit(1);
    });
}
